sudo: false

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - autoconf
      - automake
      - autotools-dev
      - bc
      - bison
      - build-essential
      - curl
      - flex
      - gawk
      - gperf
      - libgmp-dev
      - libmpc-dev
      - libmpfr-dev
      - libtool
      - patchutils
      - texinfo
      - gcc-4.8
      - g++-4.8
before_install:
  - export MAKEFLAGS="-j3"
  - export CXX=g++-4.8
  - export CC=gcc-4.8
install: true
script:
  - ./configure --prefix=/tmp/build-default
  - (make > /dev/null) || (make -j1 && exit 1)
